
jwt:
  secret:
Fcst:
  serviceKey:
naver:
  ncp:
    client-id:
    client-secret:
  developers:
    client-id:
    client-secret:
    api-access:
    api-secret:
open-ai:
  assistant-id:
  api-key:
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: password
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
  datasource:
    url: jdbc:mysql://localhost:3306/your-db-name
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always