
jwt:
  secret:
Fcst:
  serviceKey: gpqienCNGo+nr2VfAyVCH30Cyxgjg7ARvd5Gtohwb8X09LhF9taiPQQqv2KrdhOrWfApKQAA/7uzrS1qXYmA5g==

naver:
  ncp:
    client-id: cxuhltuyhr
    client-secret: D64oYDheuazj35C6uN4ozwlkwMAn3GXZRQNbFnag
  developers:
    client-id:
    client-secret:
    api-access: PYZLhSVy2anyChtu2qND
    api-secret: EIPu90VEL0CPbeOQ8e09spoUvZH2HAuv0QHfsQ6w
open-ai:
  assistant-id: asst_zzt6asioJBgxSjpMxI99hb3g
  api-key: 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
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false

  security:
    user:
      name: user
      password: password

    oauth2:
      client:
        provider:
          kakao:
            # 인가코드 받기
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # 토큰 받기
            token-uri: https://kauth.kakao.com/oauth/token
            # 사용자 정보 가져오기
            user-info-uri: https://kapi.kakao.com/v2/user/me
            # 응답에서 적당한 key 가져오기
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com./oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        registration:
          kakao:
            # REST API 키
            client-id:
            # Client Secret
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname
              - name
              - gender

          naver:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - nickname
              - email
              - gender

  datasource:
    url: jdbc:mysql://localhost:3306/your-db-name
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always